version: "3.7"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "db"   
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes: 
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    container_name: postgres_db


  django-app:
    image: milenavujicic/cloudcomputing
    restart: on-failure:10
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - VER=1
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on: 
      - db
    container_name: django_app

  django-app-2:
    image: milenavujicic/cloudcomputing
    restart: on-failure:10
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - VER=2
    ports:
      - "8001:8000"
    volumes:
      - .:/code
    depends_on: 
      - db
    container_name: django_app_2
    
  web:
    build: ./nginx
    restart: on-failure:10
    ports:
      - "8080:80"
    depends_on:
      - django-app
      - django-app-2
    
volumes:
  postgres-db-data:
